
drop table T_TTGW_WALLET;

CREATE TABLE `T_TTGW_WALLET` (
  `WALLET_ACCN_ID` varchar(35) NOT NULL,
  `WALLET_ADDR` varchar(35) NOT NULL,
  `WALLET_PASSWORD` varchar(35) NOT NULL,
  `WALLET_JSON` VARCHAR(2048) DEFAULT NULL,
  `WALLET_STATUS` varchar(10) NOT NULL,
  `WALLET_UID_CREATE` datetime DEFAULT NULL,
  `WALLET_DT_CREATE` varchar(35) DEFAULT NULL,
  `WALLET_UID_UPD` datetime DEFAULT NULL,
  `WALLET_DT_UPD` varchar(35) DEFAULT NULL,
  PRIMARY KEY (`WALLET_ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

