
drop table T_TTGW_WALLET;

CREATE TABLE `T_TTGW_WALLET` (
  `WALLET_ACCN_ID` varchar(35) NOT NULL,
  `WALLET_PRIVATE_KEY` varchar(256) NOT NULL,
  `WALLET_ADDR` varchar(128) NOT NULL,
  `WALLET_PASSWORD` varchar(128) NOT NULL,
  `WALLET_JSON` VARCHAR(2048) DEFAULT NULL,
  `WALLET_STATUS` varchar(10) NOT NULL,
  `WALLET_UID_CREATE` varchar(35) DEFAULT NULL,
  `WALLET_DT_CREATE` datetime DEFAULT NULL,
  `WALLET_UID_UPD` varchar(35) DEFAULT NULL,
  `WALLET_DT_UPD` datetime DEFAULT NULL,
  PRIMARY KEY (`WALLET_ADDR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table T_TTGW_DOCSTORE;

CREATE TABLE `T_TTGW_DOCSTORE` (
  `DOCSTORE_ACCN_ID` varchar(35) NOT NULL,
  `DOCSTORE_STORE_NAME` varchar(128) NOT NULL,
  `DOCSTORE_ADDR` varchar(128) NOT NULL,
  `DOCSTORE_NETWORK` VARCHAR(128) DEFAULT NULL,
  `DOCSTORE_RENDER_NAME` VARCHAR(128) DEFAULT NULL,
  `DOCSTORE_RENDER_TYPE` VARCHAR(128) DEFAULT NULL,
  `DOCSTORE_RENDER_URL` VARCHAR(128) DEFAULT NULL,
  `DOCSTORE_NAME` VARCHAR(128) DEFAULT NULL,
  `DOCSTORE_ISSUER_NAME` VARCHAR(128) DEFAULT NULL,
  `DOCSTORE_ISSUER_TYPE` VARCHAR(128) DEFAULT NULL,
  `DOCSTORE_ISSUER_LOCATION` VARCHAR(128) DEFAULT NULL,
  `DOCSTORE_REMARK` VARCHAR(1024) DEFAULT NULL,
  `DOCSTORE_STATUS` varchar(10) NOT NULL,
  `DOCSTORE_UID_CREATE` varchar(35) DEFAULT NULL,
  `DOCSTORE_DT_CREATE` datetime DEFAULT NULL,
  `DOCSTORE_UID_UPD` varchar(35) DEFAULT NULL,
  `DOCSTORE_DT_UPD` datetime DEFAULT NULL,
  PRIMARY KEY (`DOCSTORE_ACCN_ID`,`DOCSTORE_STORE_NAME` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table T_TTGW_DOC;

CREATE TABLE `T_TTGW_DOC` (
  `DOC_DOC_ID` varchar(128) NOT NULL,
  `DOC_ACCN_ID` varchar(35) NOT NULL,
  `DOC_STORE_NAME` varchar(128) NOT NULL,
  `DOC_WRAP_HASH` VARCHAR(128) DEFAULT NULL,
  `DOC_ADDR` varchar(128) NOT NULL,
  `DOC_WRAP_DOC` MEDIUMTEXT NOT NULL,
  `DOC_WRAP_RAW_DOC` MEDIUMTEXT DEFAULT NULL,
  `DOC_STATUS` varchar(10) NOT NULL,
  `DOC_UID_CREATE` varchar(35) DEFAULT NULL,
  `DOC_DT_CREATE` datetime DEFAULT NULL,
  `DOC_UID_UPD` varchar(35) DEFAULT NULL,
  `DOC_DT_UPD` datetime DEFAULT NULL,
  PRIMARY KEY (`DOC_DOC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table T_TTGW_AUDITLOG;

CREATE TABLE `T_TTGW_AUDITLOG` (
  `AUDT_ID` varchar(35) NOT NULL,
  `AUDT_EVENT` varchar(100) NOT NULL,
  `AUDT_TIMESTAMP` datetime NOT NULL,
  `AUDT_ACCNID` varchar(35) NOT NULL,
  `AUDT_STORE_NAME` varchar(35) DEFAULT NULL,
  `AUDT_UID` varchar(35)  NULL,
  `AUDT_UNAME` varchar(35) DEFAULT NULL COMMENT 'User name',
  `AUDT_REMOTE_IP` varchar(35) DEFAULT NULL,
  `AUDT_REQUET` MEDIUMTEXT NOT NULL,
  `AUDT_RSP_STATUS` varchar(225) DEFAULT NULL,
  `AUDT_RSP_MESSAGE` varchar(225) DEFAULT NULL,
  `AUDT_RSP_DETAILS` MEDIUMTEXT DEFAULT NULL,
  `AUDT_REMARKS` varchar(4096) DEFAULT NULL,
  PRIMARY KEY (`AUDT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
